--- # create and configure svm for Trident
- hosts: localhost
  connection: local
  gather_facts: no
  #### Variables in vars.yaml
  vars_files:
  - vars.yaml

  tasks:
  - name: Create SVM
    na_ontap_svm:
      state: "{{ state }}"
      name: "{{ netapp_svm }}"
      root_volume: "svm_{{ netapp_svm }}_root"
      root_volume_aggregate: "{{ netapp_aggregate }}"
      root_volume_security_style: unix
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      allowed_protocols: "nfs"
      aggr_list: "aggr1_{{ cluster_name }}_01,aggr1_{{ cluster_name }}_02"

  - name: Create new data interface
    na_ontap_interface:
      state: "{{ state }}"
      interface_name: "lif_{{ netapp_svm }}_nfs_01"
      home_port: "{{ homeport }}"
      home_node: "{{ cluster_name }}-01"
      role: data
      protocols: nfs
      admin_status: up
      failover_policy: local-only
      firewall_policy: mgmt
      is_auto_revert: true
      address: "{{ netdata_ipaddress }}"
      netmask: "{{ netdata_netmask }}"
      vserver: "{{ netapp_svm }}"
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"

  - name: change nfs status
    na_ontap_nfs:
      state: "{{ state }}"
      service_state: started
      vserver: "{{ netapp_svm }}"
      nfsv3: enabled
      nfsv4: disabled
      nfsv41: disabled
      tcp: enabled
      udp: enabled
      vstorage_state: disabled
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false

  - name: Create default Export Policy (any/any)
    na_ontap_export_policy_rule:
      state: "{{ state }}"
      policy_name: default
      vserver: "{{ netapp_svm }}"
      client_match: 0.0.0.0/0
      ro_rule: any
      rw_rule: none
      super_user_security: none
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false

  - name: Create User ONTAP user for trident and enable ssh
    na_ontap_user:
      state: "{{ state }}"
      name: "{{ trident_username }}"
      application: ssh
      authentication_method: password
      set_password: "{{ trident_userpassword }}"
      lock_user: no
      role_name: vsadmin
      vserver: "{{ netapp_svm }}"
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"

  - name: Create User ONTAP user for trident and enable ontapi
    na_ontap_user:
      state: "{{ state }}"
      name: "{{ trident_username }}"
      application: ontapi
      authentication_method: password
      set_password: "{{ trident_userpassword }}"
      lock_user: no
      role_name: vsadmin
      vserver: "{{ netapp_svm }}"
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"

  - name: Create User ONTAP user for trident and enable http
    na_ontap_user:
      state: "{{ state }}"
      name: "{{ trident_username }}"
      application: http
      authentication_method: password
      set_password: "{{ trident_userpassword }}"
      lock_user: no
      role_name: vsadmin
      vserver: "{{ netapp_svm }}"
      hostname: "{{ netapp_hostname }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"